---
jobs:
  - name: unit-1.9
    public: true
    serial: true
    plan:
      - get: bosh-src
      - task: unit
        file: bosh-src/ci/concourse/tasks/test-unit.yml
        config:
          params:
            RUBY_VERSION: 1.9.3

  - name: unit-2.1
    public: true
    serial: true
    plan:
      - get: bosh-src
      - task: unit
        file: bosh-src/ci/concourse/tasks/test-unit-coverage.yml
        config:
          params:
            RUBY_VERSION: 2.1.2
            CODECLIMATE_REPO_TOKEN: {{codeclimate_token}}

  - name: integration-mysql-1.9
    public: true
    serial: true
    plan:
      - get: bosh-src
        passed: [unit-1.9, unit-2.1]
      - task: ruby-1.9
        privileged: true
        file: bosh-src/ci/concourse/tasks/test-integration.yml
        config:
          params:
            DB:           mysql
            RUBY_VERSION: 1.9.3

  - name: integration-mysql-2.1
    public: true
    serial: true
    plan:
      - get: bosh-src
        passed: [unit-1.9, unit-2.1]
      - task: ruby-2.1
        privileged: true
        file: bosh-src/ci/concourse/tasks/test-integration.yml
        config:
          params:
            DB:           mysql
            RUBY_VERSION: 2.1.2

  - name: integration-postgres-1.9
    public: true
    serial: true
    plan:
      - get: bosh-src
#        passed: [unit-1.9, unit-2.1]
      - task: ruby-1.9
        privileged: true
        file: bosh-src/ci/concourse/tasks/test-integration.yml
        config:
          params:
            DB:           postgresql
            RUBY_VERSION: 1.9.3

  - name: integration-postgres-2.1
    public: true
    serial: true
    plan:
      - get: bosh-src
#        passed: [unit-1.9, unit-2.1]
      - task: ruby-2.1
        privileged: true
        file: bosh-src/ci/concourse/tasks/test-integration.yml
        config:
          params:
            DB:           postgresql
            RUBY_VERSION: 2.1.2

resources:
  - name: bosh-src
    type: git
    source:
      uri:          git@github.com:cloudfoundry/bosh.git
      branch:       ci-fix-integration-94546576
      private_key:  {{github_private_key}}
