---
platform: linux

image: docker:///bosh/integration

inputs:
- name: bosh-src

run:
  path: bosh-src/ci/tasks/rake.sh
  args: ["--trace", "go", "spec:unit", "ci:publish_coverage_report"]

params:
  COVERAGE: true
