resources:
  - name: bosh-src
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh.git
      branch: concourse-ci

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: bosh-init
    type: s3
    source:
      regexp: bosh-init-(2\.0\.7)-linux-amd64
      bucket: {{aws_s3_release_bucket}}
      region_name: {{aws_s3_release_bucket_region}}
      access_key_id: {{aws_s3_release_bucket_access_key}}
      secret_access_key: {{aws_s3_release_bucket_secret_key}}

  - name: bosh-deployments
    type: git
    source:
      uri: git@github.com:cloudfoundry/deployments-bosh.git
      branch: master
      private_key: {{github_private_key}}

  - name: aws-cpi
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release.git
      branch: master

  - name: aws-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

  - name: openstack-cpi
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release.git
      branch: master

jobs:
  - name: bats-aws-cpi
    plan:
      - aggregate:
        - get: bosh-src
          params:
            submodules: none
        - get: bosh-init
        - get: bosh-deployments
        - get: bosh-release
        - get: cpi-release
          resource: aws-cpi
        - get: stemcell-release
          resource: aws-stemcell
      - task: deploy-microbosh
        privileged: true
        file: bosh-src/bat/ci/tasks/deploy-microbosh.yml
        config:
          params:
            manifest_path: bosh-deployments/concourse/bats-pipeline/micro-aws.yml
      - task: run-bats
        file: bosh-src/bat/ci/tasks/run-bats.yml

  # - name: bats-openstack-cpi
  #   plan:
  #     - aggregate:
  #       - get: bosh
  #       - get: bosh-init
  #       - get: bosh-deployments
  #       - get: cpi-release
  #         resource: openstack-cpi
  #     - task: deploy-microbosh
  #       file: bosh/bat/ci/tasks/deploy-microbosh.yml
  #       config:
  #         params:
  #           manifest_path: bosh-deployments/concourse/bats-pipeline/micro-openstack.yml
  #     - task: run-bats
  #       file: bosh/bat/ci/tasks/run-bats.yml
