---
jobs:
  - name: unit-1.9
    public: true
    serial: true
    plan:
      - {trigger: true, get: bosh-src}

      - task: test
        file: bosh-src/ci/tasks/test-unit.yml
        config:
          params:
            RUBY_VERSION: 1.9.3

  - name: unit-2.1
    public: true
    serial: true
    plan:
      - {trigger: true, get: bosh-src}

      - task: test
        file: bosh-src/ci/tasks/test-unit.yml
        config:
          params:
            RUBY_VERSION: 2.1.6

  - name: publish-coverage
    public: true
    serial: true
    plan:
      - {trigger: true, passed: [unit-1.9, unit-2.1], get: bosh-src}

      - task: publish
        file: bosh-src/ci/tasks/publish-coverage.yml
        config:
          params:
            CODECLIMATE_REPO_TOKEN: {{codeclimate_token}}

  - name: integration-mysql-1.9
    public: true
    serial: true
    plan:
      - {trigger: true, passed: [unit-1.9, unit-2.1], get: bosh-src}

      - task: test
        privileged: true
        file: bosh-src/ci/tasks/test-integration.yml
        config:
          params:
            DB:           mysql
            RUBY_VERSION: 1.9.3

  - name: integration-mysql-2.1
    public: true
    serial: true
    plan:
      - {trigger: true, passed: [unit-1.9, unit-2.1], get: bosh-src}

      - task: test
        privileged: true
        file: bosh-src/ci/tasks/test-integration.yml
        config:
          params:
            DB:           mysql
            RUBY_VERSION: 2.1.6

  - name: integration-postgres-1.9
    public: true
    serial: true
    plan:
      - {trigger: true, passed: [unit-1.9, unit-2.1], get: bosh-src}

      - task: test
        privileged: true
        file:  bosh-src/ci/tasks/test-integration.yml
        config:
          params:
            DB:           postgresql
            RUBY_VERSION: 1.9.3

  - name: integration-postgres-2.1
    public: true
    serial: true
    plan:
      - {trigger: true, passed: [unit-1.9, unit-2.1], get: bosh-src}

      - task: test
        privileged: true
        file: bosh-src/ci/tasks/test-integration.yml
        config:
          params:
            DB:           postgresql
            RUBY_VERSION: 2.1.6

  - name: promote-candidate
    public: true
    serial: true
    plan:
      - {trigger: true, passed: [integration-mysql-1.9, integration-mysql-2.1, integration-postgres-1.9, integration-postgres-2.1], get: bosh-src}

      - {put: bosh-candidate, params: {repository: bosh-src}}

resources:
  - name: bosh-src
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh.git
      branch: develop

  - name: bosh-candidate
    type: git
    source:
      uri: git@github.com:cloudfoundry/bosh.git
      branch: candidate
      private_key: {{github_deployment_key__bosh}}
